myvar = 10
print(myvar)
print(type(myvar))
print()
myvar = ("Hello world")
print(myvar)
print(type(myvar))
print()
myvar2 = myvar
print(myvar, myvar2)
print(type(myvar), type(myvar2))
print()
print ("Is value the same?", myvar == myvar2)
print("Are the variables the same?", myvar is myvar2)
print()
print(id(myvar), id(myvar2))
print()
print("### Zmiana danych!! ###")
print()
myvar2 = myvar + "!!"
print(myvar, myvar2)
print(type(myvar), type(myvar2))
print()
print ("Is value the same?", myvar == myvar2)
print("Are the variables the same?", myvar is myvar2)
print()
print(id(myvar), id(myvar2))
print()
print("### Zmiana danych!! ###")
print()
myvar2 = myvar2[:-2]
print(myvar, myvar2)
print(type(myvar), type(myvar2))
print()
print ("Is value the same?", myvar == myvar2)
print("Are the variables the same?", myvar is myvar2)
print()
print(id(myvar), id(myvar2))